version: 2.1

orbs: 
  aws-ecr: circleci/aws-ecr@8.1.0

jobs:
  build_image:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: |
            docker build --tag=todolist:${CIRCLE_BUILD_NUM} .
            docker images 

  push_image_to_ECR:
    docker:
      - image: cimg/go:1.17
    steps:
    - checkout
    - run:
          name: push image 
          command: |
            aws ecr get-login-password --region AWS_REGION | docker login --username AWS --password-stdin AWS_ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com
            docker tag todolist:${CIRCLE_BUILD_NUM} AWS_ECR_ACCOUNT_URL/todolist:${CIRCLE_BUILD_NUM}
            docker images
            docker push AWS_ECR_ACCOUNT_URL/todolist:${CIRCLE_BUILD_NUM}

workflows:
  build_and_push_image:
    jobs:
      - build_image
      - push_image_to_ECR:
          requires:
            - build_image 