version: 2.1

image: &docker_image
  docker:
      - image: cimg/go:1.17

orbs: 
  aws-cli: circleci/aws-cli@3.1.0
  aws-ecr: circleci/aws-ecr@8.1.2

jobs:
  build_image:
    <<: *docker_image
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: |
            docker build --tag=todo-list:latest . > ~/output
            docker images 
      - persist_to_workspace:
          root: ~/
          paths:
            - output      
      
  push_to_ecr:
    <<: *docker_image
    executor: aws-cli/default 
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default 
      - setup_remote_docker
      - attach_workspace:
          at: ~/ 
      - run:
          name: push docker image to ECR
          command: |
            aws --version
            aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ECR_ACCOUNT_URL}
            docker tag todo-list:latest ${AWS_ECR_ACCOUNT_URL}/todo-list:latest
            docker images
            docker push ${AWS_ECR_ACCOUNT_URL}/todo-list:$latest

workflows:
  build_and_push_image:
    jobs:
      - build_image
      - push_to_ecr:
          requires:
            - build_image
            