version: 2.1

orbs: 
  aws-cli: circleci/aws-cli@3.1.0
  aws-ecr: circleci/aws-ecr@8.1.0

jobs:
  build_image:
    docker:
      - image: cimg/go:1.17
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: example
      - setup_remote_docker
      - run:
          name: build and push docker image
          command: |
            docker build --tag=todolist:${CIRCLE_BUILD_NUM} . 
            docker images 
            aws --version
            aws sts get-caller-identity
            cat ~/.aws/config
            cat ~/.aws/credentials
            aws configure
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin AWS_ECR_ACCOUNT_URL
            docker tag todolist:${CIRCLE_BUILD_NUM} AWS_ECR_ACCOUNT_URL/todolist:${CIRCLE_BUILD_NUM}
            docker images
            docker push AWS_ECR_ACCOUNT_URL/todolist:${CIRCLE_BUILD_NUM}
  
workflows:
  build_and_push_image:
    jobs:
      - build_image
